// models/AttendanceRecord.js
import mongoose from 'mongoose';

const AttendanceRecordSchema = new mongoose.Schema({
    enrollmentId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InternshipEnrollment',
        required: true
    },
    studentId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    internshipId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Internship',
        required: true
    },

    date: {
        type: Date,
        required: true
    },

    status: {
        type: String,
        enum: [
            'present',
            'absent',
            'late',
            'half-day',
            'sick-leave',
            'authorized-absence',
            'holiday',
            'weekend'
        ],
        required: true
    },

    // Time tracking
    checkInTime: String,
    checkOutTime: String,
    totalHours: {
        type: Number,
        min: 0,
        max: 24
    },
    expectedHours: {
        type: Number,
        default: 8
    },

    // Absence details
    reason: {
        type: String,
        maxlength: [200, 'Reason cannot exceed 200 characters']
    },
    isExcused: {
        type: Boolean,
        default: false
    },

    // Documentation
    proofDocument: {
        fileName: String,
        fileUrl: String,
        fileType: String
    },

    // System tracking
    notes: String,
    markedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    markedAt: {
        type: Date,
        default: Date.now
    },

    // Auto-generated flags
    isAutoGenerated: {
        type: Boolean,
        default: true
    },
    wasModified: {
        type: Boolean,
        default: false
    }
}, {
    timestamps: true
});

// Indexes
AttendanceRecordSchema.index({ enrollmentId: 1, date: 1 }, { unique: true });
AttendanceRecordSchema.index({ studentId: 1, date: -1 });
AttendanceRecordSchema.index({ status: 1 });
AttendanceRecordSchema.index({ date: -1 });

export default mongoose.model('AttendanceRecord', AttendanceRecordSchema);